"""Database Load JMX Template Generator.

Generates db-load.jmx using deterministic operation sequences.

Instead of Throughput Controllers (probabilistic) and separate param CSVs,
this template uses:
- CSV Data Set Config to read a pre-generated merged operation sequence CSV
- If Controllers to dispatch to the correct JDBC sampler based on op_type
- All query parameters (customer_id, order_id, etc.) come from CSV columns

CSV format (generated by orchestrator before test):
    seq_id,op_type,customer_id,order_id,status,amount,product_id,patient_id,
    account_id,start_date,end_date,ddl_table_name,ddl_column_name,
    ddl_column_type,grant_table,grant_user,new_username,new_password
    1,select_simple,1042,,,,,,,,,,,,,,,
    2,select_complex,,10023,SHIPPED,250.00,,,,,,,,,,,,
    3,insert,3012,,,150.00,,,,,,,,,,,,
    4,ddl,,,,,,,,,,ddl_test_001,notes,NVARCHAR(MAX),,,,
    ...

Distribution is baked into the CSV at generation time:
- 30% select_simple, 15% select_complex, 15% insert, 15% update,
  10% delete, 5% sensitive, 3% ddl, 3% grant, 2% create_user, 2% auth
"""

import xml.etree.ElementTree as ET

from ..elements.base import (
    create_test_plan,
    create_thread_group,
    create_setup_thread_group,
    create_teardown_thread_group,
    create_user_defined_variables,
    create_view_results_tree,
    create_summary_report,
    create_aggregate_report,
    create_hash_tree,
)
from ..elements.controllers import create_if_controller, create_csv_data_set_config
from ..elements.jdbc import (
    create_jdbc_connection_config,
    create_jdbc_sampler,
)


# Database-specific configurations
DB_CONFIGS = {
    'postgresql': {
        'driver': 'org.postgresql.Driver',
        'default_url': 'jdbc:postgresql://localhost:5432/testdb',
    },
    'mssql': {
        'driver': 'com.microsoft.sqlserver.jdbc.SQLServerDriver',
        'default_url': 'jdbc:sqlserver://localhost:1433;databaseName=testdb;trustServerCertificate=true',
    },
    'oracle': {
        'driver': 'oracle.jdbc.OracleDriver',
        'default_url': 'jdbc:oracle:thin:@localhost:1521:testdb',
    },
    'db2': {
        'driver': 'com.ibm.db2.jcc.DB2Driver',
        'default_url': 'jdbc:db2://localhost:50000/testdb',
    },
}

# DDL queries per database type
# Variables come from merged CSV columns: ddl_table_name, ddl_column_name, ddl_column_type
DDL_QUERIES = {
    'postgresql': '''DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = '${ddl_table_name}' AND column_name = '${ddl_column_name}') THEN
        EXECUTE format('ALTER TABLE %I ADD COLUMN %I %s', '${ddl_table_name}', '${ddl_column_name}', '${ddl_column_type}');
    END IF;
END $$;''',
    'mssql': '''IF NOT EXISTS (SELECT * FROM sys.columns
               WHERE object_id = OBJECT_ID('${ddl_table_name}') AND name = '${ddl_column_name}')
    EXEC('ALTER TABLE ${ddl_table_name} ADD ${ddl_column_name} ${ddl_column_type}');''',
    'oracle': '''DECLARE
    column_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO column_exists FROM user_tab_columns
    WHERE table_name = UPPER('${ddl_table_name}') AND column_name = UPPER('${ddl_column_name}');
    IF column_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ${ddl_table_name} ADD ${ddl_column_name} ${ddl_column_type}';
    END IF;
END;''',
    'db2': '''BEGIN
    DECLARE column_exists INTEGER;
    SELECT COUNT(*) INTO column_exists FROM syscat.columns
    WHERE tabname = UPPER('${ddl_table_name}') AND colname = UPPER('${ddl_column_name}');
    IF column_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ${ddl_table_name} ADD COLUMN ${ddl_column_name} ${ddl_column_type}';
    END IF;
END''',
}

# CREATE USER queries per database type
CREATE_USER_QUERIES = {
    'postgresql': "CREATE USER ${new_username} WITH PASSWORD '${new_password}'",
    'mssql': '''CREATE LOGIN ${new_username} WITH PASSWORD = '${new_password}';
CREATE USER ${new_username} FOR LOGIN ${new_username};''',
    'oracle': '''CREATE USER ${new_username} IDENTIFIED BY "${new_password}";
GRANT CONNECT TO ${new_username};''',
    'db2': '''CREATE USER ${new_username} USING '${new_password}';
GRANT CONNECT ON DATABASE TO USER ${new_username};''',
}

# SET ROLE queries per database type
SET_ROLE_QUERIES = {
    'postgresql': 'SET ROLE ${grant_user}',
    'mssql': "EXECUTE AS USER = '${grant_user}'",
    'oracle': 'SET ROLE ${grant_user}',
    'db2': 'SET SESSION AUTHORIZATION ${grant_user}',
}


def generate_db_load(db_type: str) -> ET.Element:
    """Generate the db-load.jmx test plan for a specific database type.

    Operation dispatch is driven by CSV Data Set Config:
    - Reads op_type + all query params from pre-generated merged CSV
    - If Controllers route to correct JDBC sampler
    - Same CSV reused across Base/Initial phases for determinism

    Args:
        db_type: Database type (postgresql, mssql, oracle, db2)

    Returns:
        ET.Element: Root jmeterTestPlan element
    """
    if db_type not in DB_CONFIGS:
        raise ValueError(f"Unsupported database type: {db_type}")

    db_config = DB_CONFIGS[db_type]

    # Root element
    root = ET.Element('jmeterTestPlan', {
        'version': '1.2',
        'properties': '5.0',
        'jmeter': '5.6.3'
    })

    # Outer HashTree (JMeter 5.x requires this wrapper)
    outer_tree = create_hash_tree()
    root.append(outer_tree)

    # Test Plan
    test_plan = create_test_plan(f"Database Load Test ({db_type.upper()})")
    outer_tree.append(test_plan)

    # HashTree for Test Plan children
    test_plan_tree = create_hash_tree()
    outer_tree.append(test_plan_tree)

    # User Defined Variables — DB_URL and DB_DRIVER passed at runtime via -J flags
    variables = create_user_defined_variables("User Defined Variables", {
        'THREAD_COUNT': '${__P(threads,10)}',
        'RAMP_UP_SEC': '${__P(rampup,60)}',
        'DURATION_SEC': '${__P(duration,3600)}',
        'DB_URL': '${__P(db_url,' + db_config['default_url'] + ')}',
        'DB_DRIVER': '${__P(db_driver,' + db_config['driver'] + ')}',
        'DB_USER': '${__P(db_user,test_user)}',
        'DB_PASSWORD': '${__P(db_password,Test@123)}',
        'DB_ADMIN_USER': '${__P(db_admin_user,test_admin)}',
        'DB_ADMIN_PASSWORD': '${__P(db_admin_password,Admin@789)}',
        'OPS_SEQUENCE': '${__P(ops_sequence,db_ops_sequence.csv)}',
    })
    test_plan_tree.append(variables)
    test_plan_tree.append(create_hash_tree())

    # JDBC Connection Configuration - Regular User
    jdbc_config = create_jdbc_connection_config(
        name="JDBC Connection - Regular User",
        variable_name="db_pool",
        db_url='${DB_URL}',
        driver_class='${DB_DRIVER}',
        username='${DB_USER}',
        password='${DB_PASSWORD}'
    )
    test_plan_tree.append(jdbc_config)
    test_plan_tree.append(create_hash_tree())

    # JDBC Connection Configuration - Admin User
    jdbc_admin_config = create_jdbc_connection_config(
        name="JDBC Connection - Admin User",
        variable_name="db_pool_admin",
        db_url='${DB_URL}',
        driver_class='${DB_DRIVER}',
        username='${DB_ADMIN_USER}',
        password='${DB_ADMIN_PASSWORD}'
    )
    test_plan_tree.append(jdbc_admin_config)
    test_plan_tree.append(create_hash_tree())

    # ===== setUp Thread Group - Runs FIRST to create test prerequisites =====
    setup_thread_group = create_setup_thread_group("Test Setup - Create Tables & Users")
    test_plan_tree.append(setup_thread_group)
    setup_tree = create_hash_tree()
    test_plan_tree.append(setup_tree)

    # Create DDL test tables (ddl_test_001 through ddl_test_020)
    _add_setup_ddl_tables(setup_tree, db_type)

    # Create test users for GRANT operations
    _add_setup_test_users(setup_tree, db_type)

    # ===== Main Thread Group =====
    thread_group = create_thread_group("Database Load Threads")
    test_plan_tree.append(thread_group)

    # HashTree for Thread Group children
    thread_group_tree = create_hash_tree()
    test_plan_tree.append(thread_group_tree)

    # CSV Data Set Config — reads merged operation sequence with all query params
    csv_config = create_csv_data_set_config(
        name="Operation Sequence",
        filename="${OPS_SEQUENCE}",
        variable_names="seq_id,op_type,customer_id,order_id,status,amount,product_id,patient_id,account_id,start_date,end_date,ddl_table_name,ddl_column_name,ddl_column_type,grant_table,grant_user,new_username,new_password",
    )
    thread_group_tree.append(csv_config)
    thread_group_tree.append(create_hash_tree())

    # If Controller: op_type == "select_simple"
    select_simple_if = create_if_controller(
        name="If Select Simple",
        condition='"${op_type}" == "select_simple"',
    )
    thread_group_tree.append(select_simple_if)
    select_simple_tree = create_hash_tree()
    select_simple_tree.append(create_jdbc_sampler(
        name="Select Customer by ID",
        pool_name="db_pool",
        query="SELECT customer_id, email, first_name, last_name, phone, created_at FROM customers WHERE customer_id = ?",
        query_type="Prepared Select Statement",
        parameters="${customer_id}",
        parameter_types="INTEGER"
    ))
    select_simple_tree.append(create_hash_tree())
    thread_group_tree.append(select_simple_tree)

    # If Controller: op_type == "select_complex"
    select_complex_if = create_if_controller(
        name="If Select Complex",
        condition='"${op_type}" == "select_complex"',
    )
    thread_group_tree.append(select_complex_if)
    select_complex_tree = create_hash_tree()
    select_complex_tree.append(create_jdbc_sampler(
        name="Select Orders with Customer",
        pool_name="db_pool",
        query="SELECT o.order_id, o.order_number, o.order_date, o.status, o.grand_total, c.first_name, c.last_name, c.email FROM orders o JOIN customers c ON o.customer_id = c.customer_id WHERE o.status = ? AND o.grand_total > ?",
        query_type="Prepared Select Statement",
        parameters="${status},${amount}",
        parameter_types="VARCHAR,DECIMAL"
    ))
    select_complex_tree.append(create_hash_tree())
    thread_group_tree.append(select_complex_tree)

    # If Controller: op_type == "insert"
    insert_if = create_if_controller(
        name="If Insert",
        condition='"${op_type}" == "insert"',
    )
    thread_group_tree.append(insert_if)
    insert_tree = create_hash_tree()
    insert_tree.append(create_jdbc_sampler(
        name="Insert Order",
        pool_name="db_pool",
        query="INSERT INTO orders (customer_id, status, total_amount) VALUES (?, 'PENDING', ?)",
        query_type="Prepared Update Statement",
        parameters="${customer_id},${amount}",
        parameter_types="INTEGER,DECIMAL"
    ))
    insert_tree.append(create_hash_tree())
    thread_group_tree.append(insert_tree)

    # If Controller: op_type == "update"
    update_if = create_if_controller(
        name="If Update",
        condition='"${op_type}" == "update"',
    )
    thread_group_tree.append(update_if)
    update_tree = create_hash_tree()
    update_tree.append(create_jdbc_sampler(
        name="Update Order Status",
        pool_name="db_pool",
        query="UPDATE orders SET status = ? WHERE order_id = ?",
        query_type="Prepared Update Statement",
        parameters="${status},${order_id}",
        parameter_types="VARCHAR,INTEGER"
    ))
    update_tree.append(create_hash_tree())
    thread_group_tree.append(update_tree)

    # If Controller: op_type == "delete"
    delete_if = create_if_controller(
        name="If Delete",
        condition='"${op_type}" == "delete"',
    )
    thread_group_tree.append(delete_if)
    delete_tree = create_hash_tree()
    delete_tree.append(create_jdbc_sampler(
        name="Delete Cart Items",
        pool_name="db_pool",
        query="DELETE FROM cart_items WHERE customer_id = ?",
        query_type="Prepared Update Statement",
        parameters="${customer_id}",
        parameter_types="INTEGER"
    ))
    delete_tree.append(create_hash_tree())
    thread_group_tree.append(delete_tree)

    # If Controller: op_type == "sensitive"
    sensitive_if = create_if_controller(
        name="If Sensitive",
        condition='"${op_type}" == "sensitive"',
    )
    thread_group_tree.append(sensitive_if)
    sensitive_tree = create_hash_tree()
    sensitive_tree.append(create_jdbc_sampler(
        name="Select Patient with SSN",
        pool_name="db_pool",
        query="SELECT patient_id, first_name, last_name, ssn, date_of_birth, medicare_id, address_line1, city, state, zip_code FROM patients WHERE patient_id = ?",
        query_type="Prepared Select Statement",
        parameters="${patient_id}",
        parameter_types="INTEGER"
    ))
    sensitive_tree.append(create_hash_tree())
    thread_group_tree.append(sensitive_tree)

    # If Controller: op_type == "ddl"
    ddl_query = DDL_QUERIES.get(db_type, DDL_QUERIES['postgresql'])
    ddl_if = create_if_controller(
        name="If DDL",
        condition='"${op_type}" == "ddl"',
    )
    thread_group_tree.append(ddl_if)
    ddl_tree = create_hash_tree()
    ddl_tree.append(create_jdbc_sampler(
        name="ALTER TABLE - Add Column",
        pool_name="db_pool_admin",
        query=ddl_query,
        query_type="Update Statement"
    ))
    ddl_tree.append(create_hash_tree())
    thread_group_tree.append(ddl_tree)

    # If Controller: op_type == "grant"
    grant_if = create_if_controller(
        name="If Grant",
        condition='"${op_type}" == "grant"',
    )
    thread_group_tree.append(grant_if)
    grant_tree = create_hash_tree()
    grant_tree.append(create_jdbc_sampler(
        name="Grant SELECT",
        pool_name="db_pool_admin",
        query="GRANT SELECT ON ${grant_table} TO ${grant_user}",
        query_type="Update Statement"
    ))
    grant_tree.append(create_hash_tree())
    thread_group_tree.append(grant_tree)

    # If Controller: op_type == "create_user"
    create_user_query = _get_create_user_query(db_type)
    create_user_if = create_if_controller(
        name="If Create User",
        condition='"${op_type}" == "create_user"',
    )
    thread_group_tree.append(create_user_if)
    create_user_tree = create_hash_tree()
    create_user_tree.append(create_jdbc_sampler(
        name="Create User",
        pool_name="db_pool_admin",
        query=create_user_query,
        query_type="Update Statement"
    ))
    create_user_tree.append(create_hash_tree())
    thread_group_tree.append(create_user_tree)

    # If Controller: op_type == "auth"
    # grant_user comes from CSV (populated by the sequence generator)
    auth_query = SET_ROLE_QUERIES.get(db_type, SET_ROLE_QUERIES['postgresql'])
    auth_if = create_if_controller(
        name="If Auth",
        condition='"${op_type}" == "auth"',
    )
    thread_group_tree.append(auth_if)
    auth_tree = create_hash_tree()
    auth_tree.append(create_jdbc_sampler(
        name="Set Session Role",
        pool_name="db_pool_admin",
        query=auth_query,
        query_type="Update Statement"
    ))
    auth_tree.append(create_hash_tree())
    thread_group_tree.append(auth_tree)

    # Listeners
    test_plan_tree.append(create_view_results_tree(enabled=False))
    test_plan_tree.append(create_hash_tree())

    test_plan_tree.append(create_summary_report())
    test_plan_tree.append(create_hash_tree())

    test_plan_tree.append(create_aggregate_report())
    test_plan_tree.append(create_hash_tree())

    # ===== tearDown Thread Group - Runs LAST to cleanup test artifacts =====
    teardown_thread_group = create_teardown_thread_group("Test Cleanup - Drop Tables & Users")
    test_plan_tree.append(teardown_thread_group)
    teardown_tree = create_hash_tree()
    test_plan_tree.append(teardown_tree)

    # Drop DDL test tables
    _add_teardown_ddl_tables(teardown_tree, db_type)

    # Drop test users created during load test
    _add_teardown_test_users(teardown_tree, db_type)

    return root


def _get_create_user_query(db_type: str) -> str:
    """Get the safe CREATE USER query for a database type.

    Uses IF NOT EXISTS / TRY-CATCH to handle both existence and
    permission issues gracefully during load testing.
    """
    create_user_queries_safe = {
        'postgresql': """DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${new_username}') THEN
        CREATE USER ${new_username} WITH PASSWORD '${new_password}';
    END IF;
END $$;""",
        'mssql': """BEGIN TRY
    IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = '${new_username}')
    BEGIN
        CREATE USER ${new_username} WITHOUT LOGIN;
    END
END TRY
BEGIN CATCH
    IF ERROR_NUMBER() NOT IN (15023, 15025, 15063)
        SELECT 1;
END CATCH""",
        'oracle': """BEGIN
    EXECUTE IMMEDIATE 'CREATE USER ${new_username} IDENTIFIED BY "${new_password}"';
    EXECUTE IMMEDIATE 'GRANT CONNECT TO ${new_username}';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1920 THEN NULL; ELSE RAISE; END IF;
END;""",
        'db2': """BEGIN
    DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
    EXECUTE IMMEDIATE 'CREATE USER ${new_username} USING ''${new_password}''';
    EXECUTE IMMEDIATE 'GRANT CONNECT ON DATABASE TO USER ${new_username}';
END""",
    }
    return create_user_queries_safe.get(db_type, create_user_queries_safe['postgresql'])


# ===== setUp Thread Group Helper Functions =====

def _add_setup_ddl_tables(parent_tree: ET.Element, db_type: str):
    """Create DDL test tables (ddl_test_001 through ddl_test_020) in setUp phase."""

    # Database-specific CREATE TABLE IF NOT EXISTS syntax
    create_table_queries = {
        'postgresql': "CREATE TABLE IF NOT EXISTS {table_name} (id SERIAL PRIMARY KEY, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)",
        'mssql': """IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = '{table_name}')
    CREATE TABLE {table_name} (id INT IDENTITY(1,1) PRIMARY KEY, created_at DATETIME DEFAULT GETDATE())""",
        'oracle': """BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE {table_name} (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;""",
        'db2': """BEGIN
    DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
    EXECUTE IMMEDIATE 'CREATE TABLE {table_name} (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)';
END""",
    }

    create_template = create_table_queries.get(db_type, create_table_queries['postgresql'])

    # Create tables ddl_test_001 through ddl_test_020
    for i in range(1, 21):
        table_name = f"ddl_test_{i:03d}"
        query = create_template.format(table_name=table_name)

        sampler = create_jdbc_sampler(
            name=f"Create Table {table_name}",
            pool_name="db_pool_admin",
            query=query,
            query_type="Update Statement"
        )
        parent_tree.append(sampler)
        parent_tree.append(create_hash_tree())


def _add_setup_test_users(parent_tree: ET.Element, db_type: str):
    """Create test users (test_user_1, test_user_2) for GRANT operations in setUp phase."""

    # Database-specific CREATE USER IF NOT EXISTS syntax with TRY/CATCH for permission handling
    create_user_queries = {
        'postgresql': """DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '{username}') THEN
        CREATE USER {username} WITH PASSWORD '{password}';
    END IF;
END $$;""",
        'mssql': """BEGIN TRY
    IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = '{username}')
    BEGIN
        CREATE USER {username} WITHOUT LOGIN;
    END
END TRY
BEGIN CATCH
    SELECT 1; -- Silently handle errors
END CATCH""",
        'oracle': """BEGIN
    EXECUTE IMMEDIATE 'CREATE USER {username} IDENTIFIED BY "{password}"';
    EXECUTE IMMEDIATE 'GRANT CONNECT TO {username}';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1920 THEN NULL; ELSE RAISE; END IF;
END;""",
        'db2': """BEGIN
    DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
    EXECUTE IMMEDIATE 'CREATE USER {username} USING ''{password}''';
    EXECUTE IMMEDIATE 'GRANT CONNECT ON DATABASE TO USER {username}';
END""",
    }

    create_template = create_user_queries.get(db_type, create_user_queries['postgresql'])

    # Create test users: test_user_1, test_user_2 (test_admin already exists)
    test_users = [
        ('test_user_1', 'Test@123'),
        ('test_user_2', 'Test@456'),
    ]

    for username, password in test_users:
        query = create_template.format(username=username, password=password)

        sampler = create_jdbc_sampler(
            name=f"Create User {username}",
            pool_name="db_pool_admin",
            query=query,
            query_type="Update Statement"
        )
        parent_tree.append(sampler)
        parent_tree.append(create_hash_tree())


# ===== tearDown Thread Group Helper Functions =====

def _add_teardown_ddl_tables(parent_tree: ET.Element, db_type: str):
    """Drop DDL test tables (ddl_test_001 through ddl_test_020) in tearDown phase."""

    # Database-specific DROP TABLE IF EXISTS syntax
    drop_table_queries = {
        'postgresql': "DROP TABLE IF EXISTS {table_name}",
        'mssql': "IF EXISTS (SELECT * FROM sys.tables WHERE name = '{table_name}') DROP TABLE {table_name}",
        'oracle': """BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE {table_name}';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -942 THEN NULL; ELSE RAISE; END IF;
END;""",
        'db2': """BEGIN
    DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
    EXECUTE IMMEDIATE 'DROP TABLE {table_name}';
END""",
    }

    drop_template = drop_table_queries.get(db_type, drop_table_queries['postgresql'])

    # Drop tables ddl_test_001 through ddl_test_020
    for i in range(1, 21):
        table_name = f"ddl_test_{i:03d}"
        query = drop_template.format(table_name=table_name)

        sampler = create_jdbc_sampler(
            name=f"Drop Table {table_name}",
            pool_name="db_pool_admin",
            query=query,
            query_type="Update Statement"
        )
        parent_tree.append(sampler)
        parent_tree.append(create_hash_tree())


def _add_teardown_test_users(parent_tree: ET.Element, db_type: str):
    """Drop load_user_* users created during load test in tearDown phase."""

    # Database-specific DROP USER IF EXISTS syntax
    drop_user_queries = {
        'postgresql': "DROP USER IF EXISTS {username}",
        'mssql': """IF EXISTS (SELECT * FROM sys.database_principals WHERE name = '{username}')
    DROP USER {username};
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = '{username}')
    DROP LOGIN {username};""",
        'oracle': """BEGIN
    EXECUTE IMMEDIATE 'DROP USER {username} CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1918 THEN NULL; ELSE RAISE; END IF;
END;""",
        'db2': """BEGIN
    DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
    EXECUTE IMMEDIATE 'DROP USER {username}';
END""",
    }

    drop_template = drop_user_queries.get(db_type, drop_user_queries['postgresql'])

    # Drop load test users: load_user_001 through load_user_050
    for i in range(1, 51):
        username = f"load_user_{i:03d}"
        query = drop_template.format(username=username)

        sampler = create_jdbc_sampler(
            name=f"Drop User {username}",
            pool_name="db_pool_admin",
            query=query,
            query_type="Update Statement"
        )
        parent_tree.append(sampler)
        parent_tree.append(create_hash_tree())


def save_db_load(db_type: str, output_path: str) -> str:
    """Generate and save db-load.jmx for a specific database type.

    Args:
        db_type: Database type (postgresql, mssql, oracle, db2)
        output_path: Path to save the JMX file

    Returns:
        Path to the saved file
    """
    root = generate_db_load(db_type)
    tree = ET.ElementTree(root)

    with open(output_path, 'wb') as f:
        tree.write(f, encoding='UTF-8', xml_declaration=True)

    return output_path
