"""Server File Heavy JMX Template Generator.

Generates server-file-heavy.jmx using deterministic operation sequences.

Instead of Throughput Controllers (probabilistic), this template uses:
- CSV Data Set Config to read a pre-generated merged operation sequence CSV
- If Controllers to dispatch to the correct sampler based on op_type
- File parameters (is_confidential, make_zip) come from CSV, not random preprocessor

CSV format (generated by orchestrator before test):
    seq_id,op_type,size_bracket,target_size_kb,output_format,output_folder_idx,is_confidential,make_zip,source_file_ids
    1,cpu,,,,,,,,
    2,mem,,,,,,,,
    3,file,medium,350,pdf,1,false,true,rfc2616;rfc1945
    4,cpu,,,,,,,,
    ...

Distribution is baked into the CSV at generation time:
- 35% CPU, 34% MEM, 30% file, 1% anomaly
"""

import xml.etree.ElementTree as ET
from ..elements.base import (
    create_test_plan,
    create_thread_group,
    create_user_defined_variables,
    create_header_manager,
    create_view_results_tree,
    create_summary_report,
    create_aggregate_report,
    create_hash_tree,
)
from ..elements.controllers import create_if_controller, create_csv_data_set_config
from ..elements.http import (
    create_http_defaults,
    create_cpu_sampler,
    create_memory_sampler,
    create_file_sampler,
    create_anomaly_cpu_sampler,
)


def generate_server_file_heavy(include_confidential: bool = False) -> ET.Element:
    """Generate the server-file-heavy.jmx test plan.

    Operation dispatch is driven by CSV Data Set Config:
    - Reads op_type + file params from pre-generated merged CSV
    - If Controllers route to correct sampler
    - File params (is_confidential, make_zip) come from CSV columns
    - Same CSV reused across Base/Initial phases for determinism

    Args:
        include_confidential: If True, generates the server-file-confidential
            variant (same structure, different CSV will have confidential rows)

    Returns:
        ET.Element: Root jmeterTestPlan element
    """
    template_name = (
        "Server File Heavy with Confidential Load Test"
        if include_confidential
        else "Server File Heavy Load Test"
    )

    # Root element
    root = ET.Element('jmeterTestPlan', {
        'version': '1.2',
        'properties': '5.0',
        'jmeter': '5.6.3'
    })

    # Outer HashTree (JMeter 5.x requires this wrapper)
    outer_tree = create_hash_tree()
    root.append(outer_tree)

    # Test Plan
    test_plan = create_test_plan(template_name)
    outer_tree.append(test_plan)

    # HashTree for Test Plan children
    test_plan_tree = create_hash_tree()
    outer_tree.append(test_plan_tree)

    # User Defined Variables
    variables = create_user_defined_variables("User Defined Variables", {
        'THREAD_COUNT': '${__P(threads,10)}',
        'RAMP_UP_SEC': '${__P(rampup,60)}',
        'DURATION_SEC': '${__P(duration,3600)}',
        'TARGET_HOST': '${__P(host,localhost)}',
        'TARGET_PORT': '${__P(port,8080)}',
        'OPS_SEQUENCE': '${__P(ops_sequence,ops_sequence.csv)}',
    })
    test_plan_tree.append(variables)
    test_plan_tree.append(create_hash_tree())

    # HTTP Defaults
    http_defaults = create_http_defaults()
    test_plan_tree.append(http_defaults)
    test_plan_tree.append(create_hash_tree())

    # HTTP Header Manager
    header_manager = create_header_manager()
    test_plan_tree.append(header_manager)
    test_plan_tree.append(create_hash_tree())

    # Thread Group
    thread_group = create_thread_group("Load Test Threads")
    test_plan_tree.append(thread_group)

    # HashTree for Thread Group children
    thread_group_tree = create_hash_tree()
    test_plan_tree.append(thread_group_tree)

    # CSV Data Set Config — reads merged operation sequence with file params
    csv_config = create_csv_data_set_config(
        name="Operation Sequence",
        filename="${OPS_SEQUENCE}",
        variable_names="seq_id,op_type,size_bracket,target_size_kb,output_format,output_folder_idx,is_confidential,make_zip,source_file_ids",
    )
    thread_group_tree.append(csv_config)
    thread_group_tree.append(create_hash_tree())

    # If Controller: op_type == "cpu"
    cpu_if = create_if_controller(
        name="If CPU",
        condition='"${op_type}" == "cpu"',
    )
    thread_group_tree.append(cpu_if)
    cpu_tree = create_hash_tree()
    cpu_tree.append(create_cpu_sampler("CPU Operation", duration_ms=100, intensity=0.7))
    cpu_tree.append(create_hash_tree())
    thread_group_tree.append(cpu_tree)

    # If Controller: op_type == "mem"
    mem_if = create_if_controller(
        name="If Memory",
        condition='"${op_type}" == "mem"',
    )
    thread_group_tree.append(mem_if)
    mem_tree = create_hash_tree()
    mem_tree.append(create_memory_sampler("Memory Operation", duration_ms=100, size_mb=10))
    mem_tree.append(create_hash_tree())
    thread_group_tree.append(mem_tree)

    # If Controller: op_type == "file"
    # is_confidential and make_zip are read directly from CSV columns
    file_if = create_if_controller(
        name="If File",
        condition='"${op_type}" == "file"',
    )
    thread_group_tree.append(file_if)
    file_tree = create_hash_tree()
    file_tree.append(create_file_sampler(
        "File Operation",
        is_confidential="${is_confidential}",
        make_zip="${make_zip}",
    ))
    file_tree.append(create_hash_tree())
    thread_group_tree.append(file_tree)

    # If Controller: op_type == "anomaly"
    anomaly_if = create_if_controller(
        name="If Anomaly",
        condition='"${op_type}" == "anomaly"',
    )
    thread_group_tree.append(anomaly_if)
    anomaly_tree = create_hash_tree()
    anomaly_tree.append(create_anomaly_cpu_sampler("Anomaly - High CPU", duration_ms=5000, intensity=1.0))
    anomaly_tree.append(create_hash_tree())
    thread_group_tree.append(anomaly_tree)

    # Listeners
    test_plan_tree.append(create_view_results_tree(enabled=False))
    test_plan_tree.append(create_hash_tree())

    test_plan_tree.append(create_summary_report())
    test_plan_tree.append(create_hash_tree())

    test_plan_tree.append(create_aggregate_report())
    test_plan_tree.append(create_hash_tree())

    return root


def save_server_file_heavy(output_path: str) -> str:
    """Generate and save server-file-heavy.jmx (no confidential data).

    Args:
        output_path: Path to save the JMX file

    Returns:
        Path to the saved file
    """
    root = generate_server_file_heavy(include_confidential=False)
    tree = ET.ElementTree(root)

    with open(output_path, 'wb') as f:
        tree.write(f, encoding='UTF-8', xml_declaration=True)

    return output_path


def save_server_file_confidential(output_path: str) -> str:
    """Generate and save server-file-heavy_withconfidential.jmx.

    Same JMX structure — the difference is in the CSV:
    the orchestrator generates CSVs with confidential rows when
    the scenario uses this template variant.

    Args:
        output_path: Path to save the JMX file

    Returns:
        Path to the saved file
    """
    root = generate_server_file_heavy(include_confidential=True)
    tree = ET.ElementTree(root)

    with open(output_path, 'wb') as f:
        tree.write(f, encoding='UTF-8', xml_declaration=True)

    return output_path
