"""Server File Heavy with Confidential Data JMX Template Generator.

This module is a thin redirect to server_file_heavy.py which now handles
both the regular and confidential variants. The difference between variants
is in the operation sequence CSV content (generated by the orchestrator),
not the JMX structure.
"""

from .server_file_heavy import (
    generate_server_file_heavy,
    save_server_file_confidential,
)


def generate_server_file_confidential():
    """Generate the server-file-heavy_withconfidential.jmx test plan.

    Delegates to generate_server_file_heavy(include_confidential=True).
    The JMX structure is identical — the difference is in the CSV content
    generated by the orchestrator at runtime.
    """
    return generate_server_file_heavy(include_confidential=True)
