"""Server Normal Load JMX Template Generator.

Generates server-normal.jmx using deterministic operation sequences.

Instead of Throughput Controllers (probabilistic), this template uses:
- CSV Data Set Config to read a pre-generated operation sequence CSV
- If Controllers to dispatch to the correct sampler based on op_type

CSV format (generated by orchestrator before test):
    seq_id,op_type
    1,cpu
    2,mem
    3,cpu
    4,disk
    ...

Distribution is baked into the CSV at generation time:
- 40% CPU, 30% MEM, 29% DISK, 1% anomaly
"""

import xml.etree.ElementTree as ET
from ..elements.base import (
    create_test_plan,
    create_thread_group,
    create_user_defined_variables,
    create_header_manager,
    create_view_results_tree,
    create_summary_report,
    create_aggregate_report,
    create_hash_tree,
)
from ..elements.controllers import create_if_controller, create_csv_data_set_config
from ..elements.http import (
    create_http_defaults,
    create_cpu_sampler,
    create_memory_sampler,
    create_disk_sampler,
    create_anomaly_cpu_sampler,
)


def generate_server_normal() -> ET.Element:
    """Generate the server-normal.jmx test plan.

    Operation dispatch is driven by CSV Data Set Config:
    - Reads op_type from pre-generated CSV
    - If Controllers route to correct sampler
    - Same CSV reused across Base/Initial phases for determinism

    Returns:
        ET.Element: Root jmeterTestPlan element
    """
    # Root element
    root = ET.Element('jmeterTestPlan', {
        'version': '1.2',
        'properties': '5.0',
        'jmeter': '5.6.3'
    })

    # Outer HashTree (JMeter 5.x requires this wrapper)
    outer_tree = create_hash_tree()
    root.append(outer_tree)

    # Test Plan
    test_plan = create_test_plan("Server Normal Load Test")
    outer_tree.append(test_plan)

    # HashTree for Test Plan children
    test_plan_tree = create_hash_tree()
    outer_tree.append(test_plan_tree)

    # User Defined Variables
    variables = create_user_defined_variables("User Defined Variables", {
        'THREAD_COUNT': '${__P(threads,10)}',
        'RAMP_UP_SEC': '${__P(rampup,60)}',
        'DURATION_SEC': '${__P(duration,3600)}',
        'TARGET_HOST': '${__P(host,localhost)}',
        'TARGET_PORT': '${__P(port,8080)}',
        'OPS_SEQUENCE': '${__P(ops_sequence,ops_sequence.csv)}',
    })
    test_plan_tree.append(variables)
    test_plan_tree.append(create_hash_tree())

    # HTTP Defaults
    http_defaults = create_http_defaults()
    test_plan_tree.append(http_defaults)
    test_plan_tree.append(create_hash_tree())

    # HTTP Header Manager
    header_manager = create_header_manager()
    test_plan_tree.append(header_manager)
    test_plan_tree.append(create_hash_tree())

    # Thread Group
    thread_group = create_thread_group("Load Test Threads")
    test_plan_tree.append(thread_group)

    # HashTree for Thread Group children
    thread_group_tree = create_hash_tree()
    test_plan_tree.append(thread_group_tree)

    # CSV Data Set Config — reads operation sequence
    csv_config = create_csv_data_set_config(
        name="Operation Sequence",
        filename="${OPS_SEQUENCE}",
        variable_names="seq_id,op_type",
    )
    thread_group_tree.append(csv_config)
    thread_group_tree.append(create_hash_tree())

    # If Controller: op_type == "cpu"
    cpu_if = create_if_controller(
        name="If CPU",
        condition='"${op_type}" == "cpu"',
    )
    thread_group_tree.append(cpu_if)
    cpu_tree = create_hash_tree()
    cpu_tree.append(create_cpu_sampler("CPU Operation", duration_ms=100, intensity=0.7))
    cpu_tree.append(create_hash_tree())
    thread_group_tree.append(cpu_tree)

    # If Controller: op_type == "mem"
    mem_if = create_if_controller(
        name="If Memory",
        condition='"${op_type}" == "mem"',
    )
    thread_group_tree.append(mem_if)
    mem_tree = create_hash_tree()
    mem_tree.append(create_memory_sampler("Memory Operation", duration_ms=100, size_mb=10))
    mem_tree.append(create_hash_tree())
    thread_group_tree.append(mem_tree)

    # If Controller: op_type == "disk"
    disk_if = create_if_controller(
        name="If Disk",
        condition='"${op_type}" == "disk"',
    )
    thread_group_tree.append(disk_if)
    disk_tree = create_hash_tree()
    disk_tree.append(create_disk_sampler("Disk Operation", duration_ms=100, size_mb=10))
    disk_tree.append(create_hash_tree())
    thread_group_tree.append(disk_tree)

    # If Controller: op_type == "anomaly"
    anomaly_if = create_if_controller(
        name="If Anomaly",
        condition='"${op_type}" == "anomaly"',
    )
    thread_group_tree.append(anomaly_if)
    anomaly_tree = create_hash_tree()
    anomaly_tree.append(create_anomaly_cpu_sampler("Anomaly - High CPU", duration_ms=5000, intensity=1.0))
    anomaly_tree.append(create_hash_tree())
    thread_group_tree.append(anomaly_tree)

    # Listeners
    test_plan_tree.append(create_view_results_tree(enabled=False))
    test_plan_tree.append(create_hash_tree())

    test_plan_tree.append(create_summary_report())
    test_plan_tree.append(create_hash_tree())

    test_plan_tree.append(create_aggregate_report())
    test_plan_tree.append(create_hash_tree())

    return root


def save_server_normal(output_path: str) -> str:
    """Generate and save server-normal.jmx.

    Args:
        output_path: Path to save the JMX file

    Returns:
        Path to the saved file
    """
    root = generate_server_normal()
    tree = ET.ElementTree(root)

    # Write with XML declaration
    with open(output_path, 'wb') as f:
        tree.write(f, encoding='UTF-8', xml_declaration=True)

    return output_path
